name: aegis_sentinel
description: Aegis CSG Sentinel Mobile Application
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  http: any
  socket_io_client: any
  shared_preferences: any
  flutter_bloc: any
  equatable: any
  geolocator: any
  permission_handler: any
  background_fetch: any
  audio_waveforms: any
  flutter_contacts: any
  share_plus: any
  url_launcher: any
  flutter_tts: any
  vibration: any
  torch_light: any
  sensors_plus: any
  connectivity_plus: any
  flutter_blue_plus: any
  battery_plus: any
  device_info_plus: any
  package_info_plus: any
  crypto: any
  encrypt: any
  pointycastle: any
  flutter_secure_storage: any
  path_provider: any
  supabase: ^2.13.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sounds/
    - assets/images/
